/* tslint:disable */
/* eslint-disable */
/**
 * Baby Tracker
 * Track everything your baby does
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Parent,
    ParentFromJSON,
    ParentFromJSONTyped,
    ParentToJSON,
} from './';

/**
 * 
 * @export
 * @interface ParentWithToken
 */
export interface ParentWithToken {
    /**
     * 
     * @type {Parent}
     * @memberof ParentWithToken
     */
    parent: Parent;
    /**
     * 
     * @type {string}
     * @memberof ParentWithToken
     */
    token: string;
}

export function ParentWithTokenFromJSON(json: any): ParentWithToken {
    return ParentWithTokenFromJSONTyped(json, false);
}

export function ParentWithTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParentWithToken {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parent': ParentFromJSON(json['parent']),
        'token': json['token'],
    };
}

export function ParentWithTokenToJSON(value?: ParentWithToken | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parent': ParentToJSON(value.parent),
        'token': value.token,
    };
}


