/* tslint:disable */
/* eslint-disable */
/**
 * Baby Tracker
 * Track everything your baby does
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Parent
 */
export interface Parent {
    /**
     * 
     * @type {number}
     * @memberof Parent
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Parent
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Parent
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof Parent
     */
    password: string;
}

export function ParentFromJSON(json: any): Parent {
    return ParentFromJSONTyped(json, false);
}

export function ParentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Parent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': json['email'],
        'password': json['password'],
    };
}

export function ParentToJSON(value?: Parent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'email': value.email,
        'password': value.password,
    };
}


